### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by diginfo** [eskerda/wp-sqlite-docker-compose#1]
Not really an issue, just want to say thanks, I have this working, am a big fan of sqlite and have always thought that mysql is an overkill for wordpress or any other site that cache's it's pages.

I could not get the compose to work as for some reason it was not listening on 8080 (or any other port I tried) but I was successful with docker run.

I also have https working with reverse proxy on nginx and added this to the wp_config.php:

```
define( 'WP_HOME', 'https://www.mydomain.com' );
define( 'WP_SITEURL', 'https://www.mydomain.com' );

// If we're behind a proxy server and using HTTPS, we need to alert WordPress of that fact
// see also https://wordpress.org/support/article/administration-over-ssl/#using-a-reverse-proxy
if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
	$_SERVER['HTTPS'] = 'on';
}

```

**Comment by maxmag-soft** [comment]
```
git clone https://github.com/eskerda/wp-sqlite-docker-compose
cd wp-sqlite-docker-compose
git clone https://github.com/wordpress/sqlite-database-integration
```
edit docker compose:
```
version: '3.8'
services:
  wordpress:
    image: wordpress:6.7.1-fpm-alpine
    volumes:
      - ./html:/var/www/html/
      - ./wp-config.php:/var/www/html/wp-config.php
      - ./db.php:/var/www/html/wp-content/db.php
      - ./sqlite-database-integration:/var/www/html/wp-content/plugins/sqlite-database-integration
      - ./wp-content:/var/www/html/wp-content
  nginx:
    image: nginx:1.27.3
    volumes:
      - ./fpm.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    ports:
      - 3002:80
volumes:
  wordpress:
```

docker compose up
